februarywind/Network_Team_Project

Assets/ChoiJeeSeong/CharacterMovement2.cs, Assets/ChoiJeeSeong/CoinCollecter.unity, Assets/ChoiJeeSeong/PlayerCharacterControl2.cs, Assets/ChoiJeeSeong/Resources/Character2.prefab, Assets/ChoiJeeSeong/SetColorTest.cs, Assets/ChoiJeeSeong/SetColorTest.cs.meta, Assets/Common/Player Character Animator.controller, Assets/Common/Player Character Animator.controller.meta, Assets/Common/Prefab/Player Character Mesh.prefab, Assets/Common/Prefab/Player Character Mesh.prefab.meta, Assets/Common/Script/CharacterPersonalSetting.cs, Assets/Common/Script/CharacterPersonalSetting.cs.meta, Assets/Common/Script/CustomProperty.cs
플레이어 색상 설정은 현재 SetColorTest 컴포넌트 추가시 무작위로 설정됩니다
=> 커스텀 프로퍼티로부터 플레이어 캐릭터 색상 설정

Assets/ChoiJeeSeong/GameSceneTester2.cs, Assets/ChoiJeeSeong/ILocomotion2.cs, Assets/ChoiJeeSeong/ILocomotion2.cs.meta, Assets/ChoiJeeSeong/IcySliding.physicMaterial, Assets/ChoiJeeSeong/IcySliding.physicMaterial.meta, Assets/ChoiJeeSeong/IcySliding.unity, Assets/ChoiJeeSeong/IcySliding.unity.meta, Assets/ChoiJeeSeong/IcySlidingGameScene.cs, Assets/ChoiJeeSeong/IcySlidingGameScene.cs.meta, Assets/ChoiJeeSeong/IcySlidingMovement2.cs, Assets/ChoiJeeSeong/IcySlidingMovement2.cs.meta, Assets/ChoiJeeSeong/PlayerCharacterControl2.cs, Assets/ChoiJeeSeong/Resources/Character2 IcySliding.prefab, Assets/ChoiJeeSeong/Resources/Character2 IcySliding.prefab.meta
=> 빙판처럼 미끄러지는 이동 구현

Assets/KwonMingyu/Scenes/UI temp.unity, Assets/KwonMingyu/Scenes/UI temp.unity.meta, Assets/KwonMingyu/Script/Matchmaking/BackendManager1.cs, Assets/KwonMingyu/Script/Matchmaking/LobbyPanel1.cs, Assets/KwonMingyu/Script/Matchmaking/MainPanel1.cs, Assets/KwonMingyu/Script/Matchmaking/PopUp1.cs, Assets/KwonMingyu/Script/Matchmaking/PopUp1.cs.meta, Assets/KwonMingyu/Script/Matchmaking/SighUpPanel1.cs, Assets/KwonMingyu/Script/Matchmaking/TitlePanel1.cs, Assets/KwonMingyu/Script/Waiting Room/PersonalSettingPanel1.cs, Assets/KwonMingyu/Script/Waiting Room/PlayerCard1.cs, Assets/KwonMingyu/Script/Waiting Room/WaitingRoom1.cs, ProjectSettings/EditorBuildSettings.asset
=> 매치메이킹 화면에 UI적용, 미니게임 끝난 후 대기실에 플레이어 재 생성

Assets/LeeYunJeong/Resources/TTMG_Player4.prefab, Assets/LeeYunJeong/Scripts/TPS_Scripts/TPSGameScene.cs, Assets/LeeYunJeong/Scripts/TPS_Scripts/TPSGameScene.cs.meta, Assets/LeeYunJeong/Scripts/Ttangttameokgi/GameSceneTest4.cs, Assets/LeeYunJeong/Scripts/Ttangttameokgi/PlayerController4.cs, Assets/LeeYunJeong/Scripts/Ttangttameokgi/PlayerProfileManager4.cs, Assets/LeeYunJeong/TPSGameTest.unity, Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- TPS 게임씬 생성
- 투명벽 생성
- 본인 색에 따라 바닥 색 변경 후 점수 증가
- 게임 시작전 색 변경 및 점수 증가 비활성화
- 점수 차감 (미완성)
=> LYJ -> Develop / TPS, 땅따먹기 씬 구현

Assets/Common/Prefab/Lastman Game Info Canvas.prefab, Assets/Common/Resources/Minigame Selecter.asset, Assets/Common/Script/HideAndSeekGameScene.cs, Assets/Common/Script/HideAndSeekGameScene.cs.meta
실제 게임과 같이 이미 룸에 참여한 상태로 씬에 진입한 상황을 위한 초기화 기능
=> [Feat]: 숨바꼭질 미니게임이 로비를 통해 진입했을 경우의 초기화

Assets/Common/Script/CustomProperty.cs, Assets/KwonMingyu/Script/Matchmaking/BackendManager1.cs, Assets/KwonMingyu/Script/Matchmaking/MainPanel1.cs, Assets/KwonMingyu/Script/Waiting Room/WaitingRoom1.cs
=> [Feat] 우승 시 레벨 업

Assets/LeeJeongBin/Scripts/CheckPoint3.cs, Assets/LeeJeongBin/Scripts/GameOver3.cs, Assets/LeeJeongBin/Scripts/PlayerController3.cs
* 트리거 진입시 다른 클라이언트에도 공지
* 플레이어 캐릭터가 한명만 생존했을 경우 승리 처리
=> Last Man 미니게임 승리 조건 네트워킹 처리

Assets/LeeJeongBin/Scripts/GameOver3.cs, Assets/LeeJeongBin/Scripts/PlayerController3.cs
=> [Fix]: 두 가지 게임 승리 조건이 한 게임에 동시에 발생 가능한 문제 수정

Assets/ChoiJeeSeong/Countdown Text.prefab, Assets/ChoiJeeSeong/Countdown Text.prefab.meta, Assets/ChoiJeeSeong/CountdownText.cs, Assets/ChoiJeeSeong/CountdownText.cs.meta, Assets/ChoiJeeSeong/Minigame/Coin2.prefab, Assets/ChoiJeeSeong/Minigame/CoinCollecter.unity, Assets/ChoiJeeSeong/Minigame/CoinCollecterGameScene.cs, Assets/ChoiJeeSeong/Minigame/IcySliding.unity, Assets/ChoiJeeSeong/Minigame/IcySlidingGameScene.cs, Assets/ChoiJeeSeong/Minigame/LocalPlayerTrigger2.cs
* 카운트다운 UI 프리팹 생성
* 사운드 추가에 따라 애셋 추가됨
=> [Feat]: 카운트다운, 코인 습득, 빙판 추락 사운드 추가

Assets/ChoiJeeSeong/UISound.cs, Assets/ChoiJeeSeong/UISound.cs.meta, Assets/KwonMingyu/Scenes/UI temp.unity
=> [Feat]: UI 포인터 사운드 출력 기능 및 샘플

Assets/ChoiJeeSeong/AudioMixerSettingPanel.cs, Assets/ChoiJeeSeong/AudioMixerSettingPanel.cs.meta, Assets/ChoiJeeSeong/AudioTest.unity, Assets/ChoiJeeSeong/AudioTest.unity.meta, Assets/Common/AudioMixer.mixer, Assets/Common/AudioMixer.mixer.meta, Assets/Common/Resources/GameManager.prefab, Assets/Common/Script/SoundManager.cs
=> 오디오 그룹별 사운드 설정 기능 및 UI 샘플

Assets/KwonMingyu/Scenes/UI temp.unity, Assets/KwonMingyu/Script/SoundController1.cs, Assets/KwonMingyu/Script/SoundController1.cs.meta, Assets/KwonMingyu/Script/Waiting Room/PlayerCard1.cs
=> [Feat] 사운드 설정 슬라이드 추가, 버튼에 사운드 추가

Assets/Common/Prefab/TPS Game Info Canvas.prefab, Assets/Common/Prefab/Ttang Game Info Canvas.prefab, Assets/KwonMingyu/Scenes/UI temp.unity, Assets/LeeYunJeong/Materials/Ttangttameokgi Cube.mat, Assets/LeeYunJeong/Resources/TTMG_Player4.prefab, Assets/LeeYunJeong/Scripts/Ttangttameokgi/PlayerController4.cs, Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- 땅따먹기 게임 배경 추가
- 바닥 색상 변경
- 게임 소개 캔버스 수정 (게임 이름 및 게임 설명 추가)
- 캐릭터 움직임 변경
- 기존 리지드바디 -> 캐릭터 컨트롤러
=> LYJ -> Develop / 땅따먹기 게임 씬 구현

Assets/ChoiJeeSeong/AudioMixerSettingPanel.cs, Assets/ChoiJeeSeong/AudioTest.unity, Assets/Common/Script/SoundManager.cs, Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
=> [Feat]: 음소거 기능 및 테스트 씬에 내용 추가

Assets/ChoiJeeSeong/Minigame/CoinCollecter.unity, Assets/ChoiJeeSeong/Minigame/IcySliding.unity, Assets/Common/Script/MiniGameSceneBase.cs
MiniGameSceneBase를 상속하는 씬 관리자에 인스펙터 창에서 Audio Clip 추가시 재생됨
=> [Feat]: 미니게임에 BGM 재생 추가

Assets/ChoiJeeSeong/Minigame/CoinCollecter.unity, Assets/ChoiJeeSeong/Minigame/CoinCollecterGameScene.cs, Assets/ChoiJeeSeong/Minigame/IcySliding.unity
=> [Feat]: 맵과 함께 어두워지는 스카이돔 추가, 스카이박스 추가

Assets/Common/Script/SoundManager.cs, Assets/LeeJeongBin/Scripts/AIController3.cs, Assets/LeeJeongBin/Scripts/Killing3.cs
* 라스트맨 게임 룸 오브젝트 사망시 처리 스스로 실행
* 사운드 매니저에 채널별 음소거 상태 Getter 추가
* 사운드 매니저에 채널별 음량 Getter 음소거 상태에 영향받지 않도록 변경(음소거여도 음소거 이전의 값 반환)
=> Fix/룸 오브젝트 파괴 책임 수정, 사운드매니저 수정

Assets/Common/Script/MiniGameSceneBase.cs, Assets/LeeYunJeong/Resources/TPS_Player4.prefab, Assets/LeeYunJeong/Scripts/TPS_Scripts/TPSGameScene.cs, Assets/LeeYunJeong/Scripts/TPS_Scripts/TPSPlayerController4.cs, Assets/LeeYunJeong/TPSGame.unity, Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
* 플레이어 프리팹의 AudioSource에서 추가 설정 가능합니다
* MiniGameSceneBase에 음량 설정 필드를 추가했습니다
=> [Feat]: 총기 발사 사운드 거리에 영향을 받도록 수정, BGM별 음량 설정 추가

Assets/LeeYunJeong/Scripts/TPS_Scripts/TPSGameScene.cs, Assets/LeeYunJeong/Scripts/TPS_Scripts/TPSPlayerController4.cs, Assets/LeeYunJeong/Scripts/Ttangttameokgi/TtangttameokgiGameScene.cs, Assets/LeeYunJeong/TPSGame.unity
게임 시작 카운트 프리팹 사용
TPS 게임 시작 전 공격 불가 (5초 후에 공격 가능)
=> [Feat]: 게임 시작 카운트 변경 및 게임 시작 전 공격 불가

Assets/KwonMingyu/Script/Matchmaking/BackendManager1.cs, Assets/KwonMingyu/Script/Matchmaking/LoginPanel1.cs, Assets/KwonMingyu/Script/Matchmaking/TitlePanel1.cs
* 새로운 디바이스에서 중복 로그인을 시도하면 기존에 로그인된 디바이스의 연결을 끊습니다
=> 중복 로그인 방지 기능

Assets/ChoiJeeSeong/CameraController2.cs, Assets/Common/Script/SoundManager.cs, Assets/LeeJeongBin/Scenes/LastMan.unity, Assets/LeeJeongBin/Scripts/DeathCamera3.cs, Assets/LeeJeongBin/Scripts/LastManAudio.cs, Assets/LeeJeongBin/Scripts/PlayerController3.cs
=> 라스트 맨 게임 사망시 프리카메라
